game:
    module: alphazero.games.tictactoe
    name: TicTacToe
model:
    module: alphazero.games.tictactoe
    name: AlphaZeroTTT
    kwargs:
        num_blocks: 3
        channels_per_block: 16
loss:
    module: alphazero.games.tictactoe
    name: AlphaZeroTTTLoss
training:
    num_steps: 10000
    batch_size: 64
    lr: 0.02
    momentum: 0.9
    weight_decay: 1.e-4
    lr_schedule_gamma: 0.1
    lr_schedule: [500, 2000, 4000]
selfplay:
    num_expansions_per_sim: 32
    exploration_depth: 3
    reuse_search_tree: True
